apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jcode-front
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jsh2256/jhub_frontend.git
    targetRevision: master
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: watcher
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 