apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jcode-front-hpa
  namespace: watcher
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jcode-front
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: jcode-front-pdb
  namespace: watcher
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: jcode-front
---